### ISSUE TITLE
When you click Show Image Feed from the new menu, the new menu will disappear.

### ISSUE THREAD

**Issue by wencxxxxxx** [pythongosssss/ComfyUI-Custom-Scripts#298]
![cd4af7ec-5d2d-4cc4-9ab5-8dca2e68dce7](https://github.com/user-attachments/assets/74fe7db4-9da2-4c4c-99d7-68267cd52a99)

**Comment by pythongosssss** [comment]
Are you running with the latest ComfyUI as this should be fixed

**Comment by wencxxxxxx** [comment]
> Are you running with the latest ComfyUI as this should be fixed

You can test it.

**Comment by wencxxxxxx** [comment]
I find it doesn't disappear when it's above and below

**Comment by Shingkyo** [comment]
A screen capture to supplement this. It would be good if this can be resolved.

https://github.com/user-attachments/assets/135d0713-50f5-4f48-8919-aa1d7b6e2a2b

**Comment by Kahldris** [comment]
I still have the same problem, I'd like the feed on the side but it keeps hiding the comfy menu bar. Everything is up to date from the manager.
